plugins {
    id 'base'
    alias libs.plugins.spotbugs
    alias libs.plugins.dorongold.task.tree
    alias libs.plugins.github.johnrengelman.shadow
    id 'maven-publish'
    id 'jacoco'
    alias libs.plugins.sonarqube
    id 'repositories'
}

allprojects {
    group = project.group
    version = project.version
}

subprojects {
    apply plugin: 'maven-publish'
    publishing {
        publications {
            mavenJava(MavenPublication) {
                groupId project.group
                artifactId project.name
                version = project.version
            }
        }
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/ballerina-platform/ballerina-lang")
                credentials {
                    username System.getenv("publishUser")
                    password System.getenv("publishPAT")
                }
            }
        }
    }
}

sonarqube {
  properties {
    property "sonar.projectKey", "ballerina-lang"
    property "sonar.organization", "ballerina-platform"
    property "sonar.host.url", "https://sonarcloud.io"
  }
}
